language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
    - nif2.0
install: /bin/true
script: "mvn clean install"
notifications:
  email:
    recipients:
      - sandroacoelho@gmail.com
    on_success: change 
    on_failure: change
